"""stable migration

Revision ID: 32cfacb3e3b8
Revises: f76b7935b25b
Create Date: 2024-04-02 18:43:09.954770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32cfacb3e3b8'
down_revision: Union[str, None] = 'f76b7935b25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('file_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'file_name')
    # ### end Alembic commands ###
